apiVersion: apps/v1
kind: Deployment
metadata: { name: otelbox, labels: { app: otelbox } }
spec:
  replicas: 1
  selector: { matchLabels: { app: otelbox } }
  template:
    metadata: { labels: { app: otelbox } }
    spec:
      containers:
        - name: otelbox
          image: ghcr.io/cognis-digital/otelbox:latest
          ports: [{ containerPort: 8000 }]
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "500m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata: { name: otelbox }
spec:
  selector: { app: otelbox }
  ports: [{ port: 80, targetPort: 8000 }]
